services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cataur-next-client
    ports:
      - "${APP_PORT}:${PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    restart: unless-stopped
    networks:
      - cataur-network

networks:
  cataur-network:
    driver: bridge
