services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cataur-next-client
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - cataur-network

networks:
  cataur-network:
    driver: bridge
