services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "28080:80"
    volumes:
      - ../../webapi:/srv/webapi
      - ../../next-client:/srv/frontend
      - ./filebrowser.db:/database.db
      - ./config:/config
    user: "${PUID}:${PGID}"
    security_opt:
      - no-new-privileges:true
